### PR TITLE
add tvOS support

### PR DESCRIPTION
**Pull request by vlcone**

### CODE REVIEW

**Comment by karlvr** [comment]
@vlcone Thanks

**Comment by karlvr** [comment]
@vlcone would you be able to confirm that it works correctly on tvOS? Then I will make a 1.0.1 release version.

**Comment by vlcone** [comment]
Yes, works correctly on tvOS.
Thanks for the quick merge!

**Comment by karlvr** [comment]
@vlcone wonderful, I've released v1.0.1 that includes this change.

**Pull request merged**
